### ISSUE TITLE
migrate storybook to V3

### ISSUE THREAD

**Issue by yanivefraim** [wix/yoshi#145]
1. Verify that it works
2. Notify projects that uses it / put a FT

**Comment by yardnsm** [comment]
## Todo

- [ ] Update `yoshi/config/webpack.config.storybook.js` to match webpack 2.
- [ ] If `process.env.STORYBOOK3` is set, use webpack 2 config.
- [ ] Use the scss loader in webpack 2 config.
- [ ] Remove json loader.

See: [`yardnsm/yoshi`](https://github.com/yardnsm/yoshi).

**Comment by yardnsm** [comment]
## How to migrate your project (subject to change):

1. Install and run storybook cli as follows:
```console
npm i -g @storybook/cli
cd my-storybook2-project
getstorybook
```

2. Update yoshi dependency

3. In your storybook's webpack config, correct the path to the default config:

```diff
- const genDefaultConfig = require('@kadira/storybook/dist/server/config/defaults/webpack.config.js');
+ const genDefaultConfig = require('@storybook/react/dist/server/config/defaults/webpack.config.js');
```
